apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "common.labels" . | indent 4 }}
data:
  application.properties: |-
    # Spring Actuator
    management.server.port=9001
    management.endpoints.enabled-by-default=false
    management.endpoint.info.enabled=true
    management.endpoint.health.enabled=true
    management.endpoint.health.group.readiness.include=readinessState
    management.endpoint.prometheus.enabled=true
    management.endpoints.web.exposure.include=info,health,prometheus
    management.health.redis.enabled=true

    # Logging
    logging.level.no.entur.lamassu={{ .Values.configMap.logLevel }}

    # Scheduling
    org.quartz.jobStore.class=org.quartz.simpl.RAMJobStore
    spring.quartz.job-store-type=memory

    # Redis
    spring.redis.host=${REDIS_HOST}
    spring.redis.port=6379

    # graphql starter
    graphiql.enabled=true
    graphiql.static.basePath=/mobility/v2/
    graphiql.endpoint.graphql=/mobility/v2/graphql
    graphiql.endpoint.subscriptions=/mobility/v2/subscriptions
    graphql.servlet.actuator-metrics=true
    graphql.servlet.corsEnabled=false

    # spring boot
    # Enable response compression and http2
    server.compression.enabled=true
    server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    server.compression.min-response-size=1024
    server.http2.enabled=true

    # Graceful shutdown of server
    server.shutdown=graceful

    org.entur.lamassu.feedproviders=file:/etc/application-config/feedproviders.yml
    org.entur.lamassu.baseUrl={{ .Values.configMap.baseUrl }}

    # Admin endpoint basic auth
    org.entur.lamassu.adminPassword=${ADMIN_PASSWORD}

  feedproviders.yml: |-
    {{- with .Values.lamassu.feedProviders }}
    lamassu:
      providers:
        {{- toYaml . | nindent 8 }}
    {{- end }}
